app:
  config:
    externalBankListFile: /home/kryszak/external.csv
    externalBankUri: "/accounts/{accountNumber}/history"
    bankCode: "00117298"
    externalAuth:
      user: "admin"
      password: "admin"
    client:
      connectTimeout: 5000
      readTimeout: 5000
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/home/kryszak/workspace/BSR/db/h2data
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
