
package com.bsr.services.bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.bsr.types.bank.AccountHistoryRequest;
import com.bsr.types.bank.AccountHistoryResponse;
import com.bsr.types.bank.ExternalTransferRequest;
import com.bsr.types.bank.InternalTransferRequest;
import com.bsr.types.bank.LoginRequest;
import com.bsr.types.bank.LoginResponse;
import com.bsr.types.bank.ObjectFactory;
import com.bsr.types.bank.OperationSuccessResponse;
import com.bsr.types.bank.PaymentRequest;
import com.bsr.types.bank.WithdrawalRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bank_PortType", targetNamespace = "http://bsr.com/services/bank")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankPortType {


    /**
     * 
     * @param internalTransferRequest
     * @return
     *     returns com.bsr.types.bank.OperationSuccessResponse
     */
    @WebMethod(action = "http://bsr.com/services/bank/internalTransfer")
    @WebResult(name = "OperationSuccessResponse", targetNamespace = "http://bsr.com/types/bank", partName = "InternalTransferResponse")
    public OperationSuccessResponse internalTransfer(
        @WebParam(name = "InternalTransferRequest", targetNamespace = "http://bsr.com/types/bank", partName = "InternalTransferRequest")
        InternalTransferRequest internalTransferRequest);

    /**
     * 
     * @param paymentRequest
     * @return
     *     returns com.bsr.types.bank.OperationSuccessResponse
     */
    @WebMethod(action = "http://bsr.com/services/bank/payment")
    @WebResult(name = "OperationSuccessResponse", targetNamespace = "http://bsr.com/types/bank", partName = "PaymentResponse")
    public OperationSuccessResponse payment(
        @WebParam(name = "PaymentRequest", targetNamespace = "http://bsr.com/types/bank", partName = "PaymentRequest")
        PaymentRequest paymentRequest);

    /**
     * 
     * @param withdrawalRequest
     * @return
     *     returns com.bsr.types.bank.OperationSuccessResponse
     */
    @WebMethod(action = "http://bsr.com/services/bank/withdrawal")
    @WebResult(name = "OperationSuccessResponse", targetNamespace = "http://bsr.com/types/bank", partName = "WithdrawalResponse")
    public OperationSuccessResponse withdrawal(
        @WebParam(name = "WithdrawalRequest", targetNamespace = "http://bsr.com/types/bank", partName = "WithdrawalRequest")
        WithdrawalRequest withdrawalRequest);

    /**
     * 
     * @param accountHistoryRequest
     * @return
     *     returns com.bsr.types.bank.AccountHistoryResponse
     */
    @WebMethod(action = "http://bsr.com/services/bank/accountHistory")
    @WebResult(name = "AccountHistoryResponse", targetNamespace = "http://bsr.com/types/bank", partName = "AccountHistoryResponse")
    public AccountHistoryResponse accountHistory(
        @WebParam(name = "AccountHistoryRequest", targetNamespace = "http://bsr.com/types/bank", partName = "AccountHistoryRequest")
        AccountHistoryRequest accountHistoryRequest);

    /**
     * 
     * @param externalTransferRequest
     * @return
     *     returns com.bsr.types.bank.OperationSuccessResponse
     */
    @WebMethod(action = "http://bsr.com/services/bank/externalTransfer")
    @WebResult(name = "OperationSuccessResponse", targetNamespace = "http://bsr.com/types/bank", partName = "ExternalTransferResponse")
    public OperationSuccessResponse externalTransfer(
        @WebParam(name = "ExternalTransferRequest", targetNamespace = "http://bsr.com/types/bank", partName = "ExternalTransferRequest")
        ExternalTransferRequest externalTransferRequest);

    /**
     * 
     * @param loginRequest
     * @return
     *     returns com.bsr.types.bank.LoginResponse
     */
    @WebMethod(action = "http://bsr.com/services/bank/login")
    @WebResult(name = "LoginResponse", targetNamespace = "http://bsr.com/types/bank", partName = "LoginResponse")
    public LoginResponse login(
        @WebParam(name = "LoginRequest", targetNamespace = "http://bsr.com/types/bank", partName = "LoginRequest")
        LoginRequest loginRequest);

}
